commandes-ms/src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{   
    #[Groups(['commande:read'])]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['commande:read'])]
    #[ORM\Column]
    private ?int $client_id = null;

    #[Groups(['commande:read'])]
    #[ORM\Column]
    private ?\DateTime $date = null;

    #[Groups(['commande:read'])]
    #[ORM\Column(length: 255)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->client_id;
    }

    public function setClientId(int $client_id): static
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

commandes-ms/src/Form/CommandeForm.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('client_id')
            ->add('date')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

commandes-ms/src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeForm;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/commande')]
final class CommandeController extends AbstractController
{
    #[Route(name: 'app_commande_index', methods: ['GET'])]
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commande_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeForm::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commande);
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commande/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_show', methods: ['GET'])]
    public function show(Commande $commande): Response
    {
        return $this->render('commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commande_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommandeForm::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commande/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_delete', methods: ['POST'])]
    public function delete(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
    }
}

commandes-ms/templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

commandes-ms/templates/commande/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

commandes-ms/templates/commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commande_index') }}">back to list</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}

commandes-ms/templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Client_id</th>
                <th>Date</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.clientId }}</td>
                <td>{{ commande.date ? commande.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.status }}</td>
                <td>
                    <a href="{{ path('app_commande_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commande_new') }}">Create new</a>
{% endblock %}

commandes-ms/templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande/_form.html.twig') }}

    <a href="{{ path('app_commande_index') }}">back to list</a>
{% endblock %}

commandes-ms/templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Client_id</th>
                <td>{{ commande.clientId }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ commande.date ? commande.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ commande.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commande_index') }}">back to list</a>

    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}