commandes-ms/src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FactureRepository::class)]
class Facture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $commande_id = null;

    #[ORM\Column]
    private ?float $total = null;

    #[ORM\Column]
    private ?\DateTime $date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommandeId(): ?int
    {
        return $this->commande_id;
    }

    public function setCommandeId(int $commande_id): static
    {
        $this->commande_id = $commande_id;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): static
    {
        $this->total = $total;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): static
    {
        $this->date = $date;

        return $this;
    }
}

commandes-ms/src/Form/FactureForm.php
<?php

namespace App\Form;

use App\Entity\Facture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FactureForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('commande_id')
            ->add('total')
            ->add('date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Facture::class,
        ]);
    }
}

commandes-ms/src/Controller/FactureController.php
<?php

namespace App\Controller;

use App\Entity\Facture;
use App\Form\FactureForm;
use App\Repository\FactureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/facture')]
final class FactureController extends AbstractController
{
    #[Route(name: 'app_facture_index', methods: ['GET'])]
    public function index(FactureRepository $factureRepository): Response
    {
        return $this->render('facture/index.html.twig', [
            'factures' => $factureRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_facture_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $facture = new Facture();
        $form = $this->createForm(FactureForm::class, $facture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($facture);
            $entityManager->flush();

            return $this->redirectToRoute('app_facture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture/new.html.twig', [
            'facture' => $facture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facture_show', methods: ['GET'])]
    public function show(Facture $facture): Response
    {
        return $this->render('facture/show.html.twig', [
            'facture' => $facture,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_facture_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Facture $facture, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FactureForm::class, $facture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_facture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture/edit.html.twig', [
            'facture' => $facture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facture_delete', methods: ['POST'])]
    public function delete(Request $request, Facture $facture, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$facture->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($facture);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_facture_index', [], Response::HTTP_SEE_OTHER);
    }
}

commandes-ms/templates/facture/_delete_form.html.twig
<form method="post" action="{{ path('app_facture_delete', {'id': facture.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ facture.id) }}">
    <button class="btn">Delete</button>
</form>

commandes-ms/templates/facture/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

commandes-ms/templates/facture/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Facture{% endblock %}

{% block body %}
    <h1>Edit Facture</h1>

    {{ include('facture/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_facture_index') }}">back to list</a>

    {{ include('facture/_delete_form.html.twig') }}
{% endblock %}

commandes-ms/templates/facture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture index{% endblock %}

{% block body %}
    <h1>Facture index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Commande_id</th>
                <th>Total</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for facture in factures %}
            <tr>
                <td>{{ facture.id }}</td>
                <td>{{ facture.commandeId }}</td>
                <td>{{ facture.total }}</td>
                <td>{{ facture.date ? facture.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_facture_show', {'id': facture.id}) }}">show</a>
                    <a href="{{ path('app_facture_edit', {'id': facture.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_facture_new') }}">Create new</a>
{% endblock %}

commandes-ms/templates/facture/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Facture{% endblock %}

{% block body %}
    <h1>Create new Facture</h1>

    {{ include('facture/_form.html.twig') }}

    <a href="{{ path('app_facture_index') }}">back to list</a>
{% endblock %}

commandes-ms/templates/facture/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture{% endblock %}

{% block body %}
    <h1>Facture</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ facture.id }}</td>
            </tr>
            <tr>
                <th>Commande_id</th>
                <td>{{ facture.commandeId }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ facture.total }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ facture.date ? facture.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_facture_index') }}">back to list</a>

    <a href="{{ path('app_facture_edit', {'id': facture.id}) }}">edit</a>

    {{ include('facture/_delete_form.html.twig') }}
{% endblock %}